---
ID: "0aad2a6a-023c-45a1-808f-a2c0e491451c"
Parent: "53bf6fd5-1d1e-a19a-dbc9-5ecc753c509a"
Template: "85adbf5b-e836-4932-a333-fe0f9fa1ed1e"
Path: /sitecore/templates/Branches/TTT/Project
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190620T140722Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
