---
ID: "6f23c7de-8f72-4156-b6f1-8ee2fa4e5a15"
Parent: "5cdc2762-eb6a-481c-8478-c6f31f62738b"
Template: "5cdc2762-eb6a-481c-8478-c6f31f62738b"
Path: /sitecore/templates/TTT/Project/TTT/Content Page/__Standard Values
DB: master
SharedFields:
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{E87794E7-2D2E-40AB-A8D7-171D6C5C54E3}">
        <r
          id="{69237B5E-2310-4805-AAF8-86922EFDD058}"
          ph="ttt-main"
          uid="{35DDC3C6-EE7B-4A50-B773-4B0FD800D4C8}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210306T204443Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
